name: IntelDMGBuild

on:
  workflow_dispatch

jobs:
  build:
    runs-on: macos-15-intel
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '22' # Or your project's version
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create local.properties file
        run: |
          echo 'email="${{ secrets.APPLE_EMAIL }}"' >> local.properties
          echo 'password="${{ secrets.APPLE_PASSWORD }}"' >> local.properties
          echo 'teamId="${{ secrets.APPLE_TEAM_ID }}"' >> local.properties

      - name: Check local.properties file
        run: |
          cat local.properties

      - name: Create FirebaseSecrets.kt file
        run: |
          run: echo "${{ secrets.FIREBASE_SECRETS }}" | base64 --decode > src/commonMain/kotlin/jatx/expense/manager/data/firebase/FirebaseSecrets.kt

      - name: MacOS info
        run: |
          sw_vers
          sysctl -n machdep.cpu.brand_string

      - name: Build DMG
        # Replace :composeApp if your module name is different (e.g., :desktop)
        run: ./gradlew :packageReleaseDmg

      - name: Rename DMG
        run: |
          mv build/compose/binaries/main-release/dmg/ExpenseManager-1.0.0.dmg build/compose/binaries/main-release/dmg/ExpenseManager-intel-1.0.0.dmg

      - name: Upload DMG Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-DMG-Intel
          path: build/compose/binaries/main-release/dmg/ExpenseManager-intel-1.0.0.dmg
          retention-days: 5